{
 "title": "Scratchpad",
 "description": "Monitoring Scratchpad Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "server_id", "label": "server_id", "query": { "query": "label_values(server_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(scratchpad:avg_generation_throughput_toks_per_s{server_id='default'}[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "Waiting Requests",
   "type": "timeseries",
   "description": "Number of waiting requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(scratchpad:num_requests_waiting{server_id='default'}[$__rate_interval])",
     "legendFormat": "Waiting Requests"
    }
   ]
  },
  {
   "title": "Memory Pool Usage (Percent)",
   "type": "timeseries",
   "description": "Memory pool usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(scratchpad:mempool_usage_percent{server_id='default'}[$__rate_interval])",
     "legendFormat": "Memory Pool Usage Percent"
    }
   ]
  },
  {
   "title": "Running Requests",
   "type": "timeseries",
   "description": "Number of running requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(scratchpad:num_requests_running{server_id='default'}[$__rate_interval])",
     "legendFormat": "Running Requests"
    }
   ]
  }
 ]
}