name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: rtx3090x1
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        bash docker/build_image.sh dev docker

    - name: Run tests in Docker container
      run: |
        # Run your test suite inside the Docker container
        # Replace this with your actual test command
        docker run scratchpad-dev:latest python -m pytest tests/

    - name: Docker image cleanup
      if: always()
      run: |
        docker image prune -f
